FROM rust:trixie AS builder
WORKDIR /usr/src/lls
COPY . .
RUN cargo install --path ./server

FROM debian:bookworm-slim
RUN apt-get update -y
RUN apt-get install -y libssl3
RUN rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/lls /usr/local/bin/lls
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/lls"]
