ALTER TABLE sessions
    ADD COLUMN start_time_stamp TIMESTAMPTZ NOT NULL DEFAULT '1970-01-01T00:00:00.000000Z',
    ADD COLUMN end_time_stamp TIMESTAMPTZ;

ALTER TABLE sessions ALTER COLUMN start_time_stamp DROP DEFAULT;
